data:
  raw_data_path: "data/raw/meta.csv"
  processed_data_path: "data/processed/"
  train_test_split: 0.2
  validation_split: 0.1
  random_seed: 42

preprocessing:
  max_features: 10000
  min_df: 2
  max_df: 0.95
  ngram_range: [1, 2]
  remove_stopwords: true
  lemmatization: true

model:
  input_dim: 10000
  hidden_dim: 256
  output_dim: 5
  dropout_rate: 0.3
  batch_size: 32
  learning_rate: 0.001

federated:
  num_clients: 5
  num_rounds: 10
  local_epochs: 2
  min_clients_per_round: 3
  privacy:
    epsilon: 1.0
    delta: 1e-5
    noise_multiplier: 1.0
    max_grad_norm: 1.0

deployment:
  host: "0.0.0.0"
  port: 5000
  debug: false
  model_path: "models/final_model.pth"
  batch_size: 16
  timeout: 30
